name: Preview

on:
  push:
    branches:
      - main

jobs:
  preview:
    name: Preview
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: jj-aarch64-apple-darwin
            exe_ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
        env:
          CARGO_TERM_COLOR: always
          JJ_PREVIEW: "1"

      - name: Upload preview binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/jj${{ matrix.exe_ext }}
          asset_name: ${{ matrix.asset_name }}
          tag: preview
          release_name: Preview
          prerelease: true
          overwrite: true
